name: Lembrete Classificador NEXT

on:
  schedule:
    - cron: '0 12 31 7,12 *'
  workflow_dispatch:

jobs:
  mandar-lembrete:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar notificação via Ntfy
        run: |
          curl -d "Hora de rodar o classificador.py e organizar os circuitos do NEXT! ♟️" \
               -H "Title: Lembrete: Xadrez NEXT" \
               -H "Tags: chess_pawn,warning" \
               -H "Email: ${{ secrets.MEU_EMAIL_NTFY }}" \
               -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
               https://ntfy.sh/alerta_next_xadrez_7788